### ISSUE TITLE
Use react.i18next

### ISSUE THREAD

**Issue by JumpAttacker** [marceloaugusto80/electron-react-typescript-boilerplate#10]
First of all thanks for boilerplate

**Describe the bug**
When im trying to use react.i18next i got errors 

**To Reproduce**
1. git clone this repo
2. npm i
3. npm install react-i18next i18next
4. create file in src i18n.ts
5. put this in file
```
import i18n from "i18next";
import {initReactI18next} from "react-i18next";

i18n
    .use(initReactI18next) // passes i18n down to react-i18next
    .init({
        resources: {
            en: {
                translation: {
                    "Welcome to React": "Welcome to React and react-i18next"
                }
            }
        },
        lng: "en",
        fallbackLng: "en",

        interpolation: {
            escapeValue: false
        }
    });

```
4. go to render-process.tsx
5. type 
```import './i18n'```
6. then try to start
7. got errors in console

**Screenshots**
![image](https://user-images.githubusercontent.com/10989729/97078509-59a3a600-15f5-11eb-81a0-d05f92ab8077.png)

these steps i take from https://react.i18next.com/getting-started

repo with bug
https://github.com/JumpAttacker/TestElectron

**Comment by marceloaugusto80** [comment]
hi, brother.

I was able to reproduce the problem.

To fix it, I added two babel packages:

`npm i -D @babel/plugin-transform-runtime @babel/runtime`

in webpack.config.js, in the renderer transpiliation part, I added the transform-runtime plugin:


```
test: /\.(js|jsx|ts|tsx)$/,
                    exclude: /node_modules/,
                    use: {
                        loader: "babel-loader",
                        options: {
                            presets: [
                                "@babel/preset-typescript",
                                "@babel/preset-react",
                                "@babel/preset-env"
                            ],
                            plugins: [
                                "@babel/plugin-proposal-class-properties",
                                "@babel/plugin-transform-runtime"
                            ]
                        }
                    }

```

take a look in the issue_10 branch.

See if it works for you.

**Comment by JumpAttacker** [comment]
Thanks! Now its working fine
