### ISSUE TITLE
Use Assets (image, font)

### ISSUE THREAD

**Issue by Jeremy38100** [marceloaugusto80/electron-react-typescript-boilerplate#8]
Hello,

Thanks for this respository, I did not succeed to use assets (font or image) in the App.
Can you help me if you have some time ?

Thanks

**Comment by marceloaugusto80** [comment]
hi, brother!

I just pushed some changes in the master-branch.

After all, I used webpack's url-loader to import font and image files. It converts assets to base64 data.

beyond that, I created ./src/types/image.d.ts file so Typescript won't complain about importing image files. There's an example in ./src/views/BarView.tsx.
